<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Todolist\Module'                        => __DIR__ . '/Module.php',
    'Todolist\Controller\TodolistController' => __DIR__ . '/src/Todolist/Controller/TodolistController.php',
    'TodolistTest\Framework\TestCase'        => __DIR__ . '/tests/Todolist/Framework/TestCase.php',
    'TodolistTest\SampleTest'                => __DIR__ . '/tests/Todolist/SampleTest.php',
);
