<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<!-- Filename: /module/Blog/view/blog/write/add.phtml -->
 <h1>WriteController::addAction()</h1>
 <?php
 $form = $this->form;
 //$form->setAttribute('method', 'GET');
 $form->setAttribute('action', $this->url());
 $form->prepare();

 echo $this->form()->openTag($form);

 echo $this->formCollection($form);

 echo $this->form()->closeTag();
 ?>
</body>
</html>