<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body> <h1>Blog</h1>

<p><a href="<?php echo $this->url('blog/add', array( 
        'action'=>'add'));?>">Add new Blog</a></p>
 <?php foreach ($this->posts as $post): ?>
 <article>
     <h1 id="post<?= $post->getId() ?>"><?= $post->getTitle() ?></h1>
     <p>
         <?= $post->getText() ?>
     </p>
 </article>
 <?php endforeach ?>

</body>
</html>