<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MyException\Module'                        => __DIR__ . '/Module.php',
    'MyException\Controller\MyExceptionController' => __DIR__ . '/src/MyException/Controller/MyExceptionController.php',
    'MyExceptionTest\Framework\TestCase'        => __DIR__ . '/tests/MyException/Framework/TestCase.php',
    'MyExceptionTest\SampleTest'                => __DIR__ . '/tests/MyException/SampleTest.php',
);
